### ISSUE TITLE
Change Tables Names

### ISSUE THREAD

**Issue by kavitama** [cornernote/yii-account-module#5]
Hi @cornernote / @zainengineer ,
I am starting enjoying what you have done with this extension/module.

I understood that the modelMap() can be used to change tables names but I am not able to understand what is the syntax expected to do such a change.

Would you please write down an example of that?
Or add it to the documentation?

**Comment by cornernote** [comment]
Should be something like this:

```
$config['modules']['account']['modelMap'] = array(
	'AccountUser' => array(
		'tableName' => 't_account_user', // custom table name
		'relations' => array(),          // extra relations
		'behaviors' => array(),          // extra behaviors
	),
);
```

**Comment by kavitama** [comment]
Same thing is for account_user_hybrid_auth table that is part of this module?

$config['modules']['account']['modelMap'] = array(
	'AccountUserHybridAuth' => array(
		'tableName' => 't_account_user_hybrid_auth', // custom table name
		'relations' => array(),          // extra relations
		'behaviors' => array(),          // extra behaviors
	),
);

**Comment by cornernote** [comment]
yep, just add all of those that you want in different tables to your yii
config


-- Brett

**Comment by kavitama** [comment]
@cornernote 
I was going to ask in a different issue but modelMap can also be used for token / email_spool / email_template tables ???

**Comment by cornernote** [comment]
Yep, all the models extend from AccountActiveRecord, which provides this
functionality.


-- Brett

**Comment by kavitama** [comment]
Strange...
I added 
```
                'EmailSpool' => array(
                    'tableName' => 'sys_email_spool',
                ),
                'EmailTemplate' => array(
                    'tableName' => 'sys_email_template',
                ),
```
but i get the following error
missing EmailTemplate - account_welcome  while if ia rename back tables to their preious name it is working

Do the modelmap have to be defined into the email module section?

**Comment by cornernote** [comment]
Those models are for the Email Module, not for the Account Module.  Make
sure you have the ModelMap in the right module.


-- Brett

**Comment by kavitama** [comment]
Yes I already did it
Added the modelMap into the Email module and all is fine now

Not sure what to do with the token table?????

**Comment by cornernote** [comment]
It's used by the account module when a user loses their password.

What do you want to do to it?


-- Brett

**Comment by kavitama** [comment]
Sorry, I didnt explained very well
I was trying to say "where do I have to put the modelmap to rename token table?"

Within the account module or in a new token module? (config/main.php)

**Comment by kavitama** [comment]
Also becasue if I try to recover password i get the following

Property "CWebApplication.tokenManager" is not defined

**Comment by cornernote** [comment]
It is it's own component

    'components' => array(
        'tokenManager' => array(
            'class' =>
'vendor.cornernote.yii-token-manager.token-manager.components.ETokenManager',
            'connectionID' => 'db',
        ),
    ),

It has a migration file here:
https://github.com/cornernote/yii-token-manager/blob/master/token-manager/migrations/token.mysql



-- Brett

**Comment by kavitama** [comment]
I already created token table using that migration
Now I renamed and changed configuration file like follows:
```
        'tokenManager' => array(
            'class' => 'vendor.cornernote.yii-token-manager.token-manager.components.ETokenManager',
            'connectionID' => 'db',
            'tokenTableName' => 'sys_token',
        ),
```
It works in the sense that it allows me to ask for a change (captcha included) and sends the email but the link is wrong.

It hink I have to change the email template...

**Comment by kavitama** [comment]
NO
The template is ok
It is the url passed that is wrong
http://testing.com.ar/yii-1.1.17/account/user/resetPassword/user_id/2/token/46738002d5697008bc336a2b11543854
but it should be 
http://testing.com.ar/yii-1.1.17/account/resetPassword/user_id/2/token/46738002d5697008bc336a2b11543854

Not sure where this has to be changed or is it a bug ?

**Comment by kavitama** [comment]
line 29 of AccountEmailManager.php in the yii-account-module/account/components folder has a fixed link set to account/user ...

**Comment by cornernote** [comment]
Can you send a PR with the fix?

**Comment by kavitama** [comment]
Hope I did it correctly

**Comment by cornernote** [comment]
I didn't see a pr come through
