### ISSUE TITLE
User Management

### ISSUE THREAD

**Issue by kavitama** [cornernote/yii-account-module#6]
Hi @cornernote / @zainengineer ,

There are two things that are unclear to me, related to user management:

1. how to enable hybridAuth since the link is wrong and am not able to get it
2. There is no CRUD for account_user table, meaning I have to extend the module to have such a fucntion or simply is well hidden ?

**Comment by cornernote** [comment]
In future, can you please create separate issues for unrelated questions?

1. What do you mean the link is wrong?

2. This module is not intended to be a user manager (for an administrator), it is expected you already have that, or create it yourself.  Instead the purpose of this is to give users the ability to manage their own account (login, change pass, etc, etc)

**Comment by kavitama** [comment]
@cornernote 
OK I will open another issue for point one and give details.
Any suggestion fro user management (that could be integrated with your yii-account-module)?

**Comment by cornernote** [comment]
I just make my own... It's not much more than a standard crud.


-- Brett
